//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

== Installing Components [[camel-installing]]

Camel comes with over 80 components, so you can imagine that we don't install all of them by default.  This section shows you how to find available components and how to install them at runtime.

=== List available components
Camel components are available as installable features.  You can look at the full list of available features using the _features:list_ command, using _grep_ to limit things down to features related to camel:

[source,text]
----
karaf@root> features:list | grep camel
[installed  ] [${camel.version}    ] camel                                repo-0
[installed  ] [${camel.version}    ] camel-core                           repo-0
[installed  ] [${camel.version}    ] camel-spring                         repo-0
[installed  ] [${camel.version}    ] camel-blueprint                      repo-0
[uninstalled] [${camel.version}    ] camel-test                           repo-0
[uninstalled] [${camel.version}    ] camel-cxf                            repo-0
[uninstalled] [${camel.version}    ] camel-cache                          repo-0
[uninstalled] [${camel.version}    ] camel-castor                         repo-0
...
----

The items marked with *_installed_* in the first column have already been installed and are available for use in your Camel routes.

=== Install and uninstalling components
You can use _features:install_ to install any component on the list.

An example: to install the _camel-cache_ component
[source,text]
----
karaf@root> features:install camel-cache
----

Similarly, you can also uninstall components that you're no longer using with _features:uninstall_
[source,text]
----
karaf@root> features:uninstall camel-cache
----
